# Generated by Django 4.0.4 on 2022-04-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowned', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investors',
            name='image_link',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='investors',
            name='desc',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='investors',
            name='link',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='investors',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
