# Generated by Django 4.0.4 on 2022-04-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowned', '0002_investors_image_link_alter_investors_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investors',
            name='payment',
            field=models.CharField(choices=[('Payment_done', 'Payment Done')], default='', max_length=20),
        ),
    ]
