# Generated by Django 4.0.4 on 2022-04-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowned', '0003_investors_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investors',
            name='payment',
            field=models.CharField(blank=True, choices=[('Payment_done', 'Payment Done')], max_length=20),
        ),
    ]
