# Generated by Django 4.0.4 on 2022-05-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Knowned', '0004_alter_investors_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investors',
            name='payment',
            field=models.CharField(choices=[('Payment_done', 'Payment Done'), ('Payment_not_done', 'Payment Not Done')], default='Payment_not_done', max_length=20),
        ),
    ]
